name: Selenium Task Every 5 Minutes

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            chromium-browser \
            chromium-chromedriver \
            xvfb \
            libnss3 \
            libgdk-pixbuf2.0-0 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libxss1 \
            libappindicator3-1 \
            libx11-xcb1 \
            libgbm1
          pip install -r requirements.txt

      - name: Set up virtual display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &  # Start virtual display
          export DISPLAY=:99

      - name: Verify Chrome installation
        run: |
          which google-chrome
          google-chrome --version

      - name: Run the script
        env:
          DISPLAY: :99  # Pass the DISPLAY variable to the script
        run: python your_script.py

      - name: View ChromeDriver Logs
        if: failure()
        run: cat /tmp/chromedriver.log

